FROM python:3.9-slim

WORKDIR /app

COPY requirement.txt requirement.txt


RUN pip install --upgrade pip


RUN pip install -r requirement.txt

COPY . .


CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
